# Generated by Django 4.2.28 on 2026-02-12 08:27

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(upload_to=contracts.models.contract_document_directory_path)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
