# Generated by Django 4.2.28 on 2026-02-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertising_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertising_campaigns.advertisingcampaign')),
            ],
        ),
    ]
